### ISSUE TITLE
Start using semver

### ISSUE THREAD

**Issue by djui** [heroku/x#51]
9825c2a broke the API. I think it's time to use semantic version.

**Comment by djui** [comment]
Another, subtle, breaking change was introduce by aab18502902d8e52a76e464b290afaa35772599c specifically with this note:

>Report is now synchronous, pushing that off to the caller if they directly use
Report. onload is unaffected. Cleaned up examples to reflect this.

Our services failed to start up and we only saw:

```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

**Comment by freeformz** [comment]
We are now tagging releases using semver, but we're also under v1.0, so things will still be in-flux. We'll always try to minimize compatibility problems (in order to save everyone, including ourselves pain), but won't be making a commitment to any APIs until we hit a v1 (assuming we ever do).
