### ISSUE TITLE
Cannot compile hmetrics with a Go modules application

### ISSUE THREAD

**Issue by gaffneyc** [heroku/x#94]
Following the instructions [on setting up Go runtime metrics](https://devcenter.heroku.com/articles/language-runtime-metrics-go#getting-started) and I'm getting the below error.

It seems like heroku/x is brining in golangci-lint?  That seems... wrong given that I'm just trying to add the metrics endpoint.

```go
go: github.com/heroku/x@v0.0.8 requires
        github.com/golangci/golangci-lint@v1.17.1 requires
        github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540: invalid pseudo-version: does not match version-control timestamp (2019-05-26T07:48:19Z)
```

**Comment by freeformz** [comment]
@gaffneyc I bumped golangci-lint to v1.18.0, which fixes the transitive invalid module info.

We will consider other options to isolate the tools further though.

**Comment by gaffneyc** [comment]
That would be great. I've just updated to master and it's still pulling all of the dependencies for golang-ci into go.sum. Considering that the hmetrics package doesn't have any dependencies outside of the standard lib it is an annoying surprise.

```
 go.mod |   5 ++---
 go.sum | 131 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------
 2 files changed, 124 insertions(+), 12 deletions(-)
```
